version: 2
 
sources:
  - name: raw_qwt
    database: QWT_ANALYTICS_DEV
    schema: RAW_DEV
    tables:
      - name: raw_customers
      
      - name: raw_employees

      - name: raw_offices

      - name: raw_shipments

      - name: raw_orders

      - name: raw_order_details

      - name: raw_products
      
      
 